version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ledger_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-ledger_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-ledger_db}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ledger_network

  postgres_test:
    image: postgres:16-alpine
    container_name: ledger_test_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_ledger_db
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d test_ledger_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ledger_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ledger_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
      - postgres_test
    networks:
      - ledger_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  ledger_network:
    driver: bridge 